"""Signal models — Derived and Estimated data structures."""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class DataCategory(str, Enum):
    """Classification of data origin."""
    OBSERVED = "observed"      # Direct from MT5
    DERIVED = "derived"        # Calculated from observed
    ESTIMATED = "estimated"    # Inferred/modeled


class SignalType(str, Enum):
    """Types of signals generated by engines."""
    VOLUME_SPIKE = "volume_spike"
    VOLUME_IMBALANCE = "volume_imbalance"
    LIQUIDITY_ZONE = "liquidity_zone"
    ABSORPTION = "absorption"
    STOP_HUNT = "stop_hunt"
    FAKE_BREAKOUT = "fake_breakout"


class Signal(BaseModel):
    """Base signal model."""
    
    timestamp: datetime
    signal_type: SignalType
    price_level: float
    confidence: float = Field(ge=0.0, le=1.0)
    data_category: DataCategory
    description: str = ""
    metadata: dict = Field(default_factory=dict)


class VolumeSignal(BaseModel):
    """Volume engine output — DERIVED data."""
    
    timestamp: datetime
    price: float
    tick_volume: int
    relative_volume: float = Field(description="Volume relative to average")
    is_spike: bool = False
    imbalance: float = Field(
        default=0.0,
        description="Buy/sell volume imbalance estimate"
    )
    data_category: DataCategory = DataCategory.DERIVED
    
    # Imbalance is ESTIMATED since we infer direction from tick data
    @property
    def imbalance_category(self) -> DataCategory:
        return DataCategory.ESTIMATED


class LiquidityZone(BaseModel):
    """Liquidity zone — ESTIMATED data."""
    
    price_low: float
    price_high: float
    strength: float = Field(ge=0.0, le=1.0)
    zone_type: str = Field(description="support/resistance/session")
    touches: int = 0
    last_touch: Optional[datetime] = None
    data_category: DataCategory = DataCategory.ESTIMATED
    
    @property
    def midpoint(self) -> float:
        return (self.price_low + self.price_high) / 2


class AbsorptionSignal(BaseModel):
    """Absorption detection — ESTIMATED data."""
    
    timestamp: datetime
    price_level: float
    volume_ratio: float = Field(description="Volume vs average")
    price_movement: float = Field(description="Price movement in pips")
    defense_count: int = Field(description="Times level was defended")
    confidence: float = Field(ge=0.0, le=1.0)
    direction: str = Field(description="bullish/bearish absorption")
    data_category: DataCategory = DataCategory.ESTIMATED


class StopHuntSignal(BaseModel):
    """Stop hunt detection — ESTIMATED data."""
    
    timestamp: datetime
    trigger_price: float
    extreme_price: float
    reversal_price: float
    hunt_direction: str = Field(description="above/below")
    volume_at_extreme: float
    reversal_speed: float = Field(description="Pips per bar on reversal")
    confidence: float = Field(ge=0.0, le=1.0)
    data_category: DataCategory = DataCategory.ESTIMATED


class FakeBreakoutSignal(BaseModel):
    """Fake breakout detection — ESTIMATED data."""
    
    timestamp: datetime
    breakout_price: float
    extreme_price: float
    return_price: float
    breakout_direction: str = Field(description="up/down")
    continuation_strength: float = Field(
        description="How weak the continuation was (0-1)"
    )
    bars_outside: int
    confidence: float = Field(ge=0.0, le=1.0)
    data_category: DataCategory = DataCategory.ESTIMATED